### ISSUE TITLE
Figure out routes in react 

### ISSUE THREAD

**Issue by Houghelpuff** [Houghelpuff/roomate.io#2]
React routes are broken right now so we have to figure out how to get the routes to render different components

**Comment by Houghelpuff** [comment]
React router only installed in the branch `react-router`. It's getting an error:
`TypeError: undefined is not an object (evaluating 'props.history.location')`
and I can't figure out how to fix it. That's where were at here

**Comment by ArcaneWizard** [comment]
Just ran your code real quick. That error was happening because of a subtle import typo. 
In your App.js file, try changing this:
```JS
import { BrowserRouter as Switch, Router, Route } from "react-router-dom";
```
to this:
``` JS
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
````

**Comment by Houghelpuff** [comment]
Oh my gosh, you're incredible @ArcaneWizard 😭 thanks a bunch!
